name: rowtoparis24
static_sites:
- build_command: rm -r ./public; hugo --destination ./public
  environment_slug: hugo
  github:
    branch: main
    deploy_on_push: true
    repo: uia-worker/rowtoparis24
  name: rowtoparis24
